// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDikAE3m7oz76frgBJzd1rOUtBD51rTcwI',
    appId: '1:464056634750:web:a883ea0201db35721ab72f',
    messagingSenderId: '464056634750',
    projectId: 'agritek-c8b4f',
    authDomain: 'agritek-c8b4f.firebaseapp.com',
    storageBucket: 'agritek-c8b4f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrNj63wF94TmfXGy7Hz48rrp-KxJjl2xM',
    appId: '1:464056634750:android:4d8ded267a1382b91ab72f',
    messagingSenderId: '464056634750',
    projectId: 'agritek-c8b4f',
    storageBucket: 'agritek-c8b4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9ZFfWaYn8ZrAYSZU25b47P-n1sFRY1Dk',
    appId: '1:464056634750:ios:4f18d60edd1fadce1ab72f',
    messagingSenderId: '464056634750',
    projectId: 'agritek-c8b4f',
    storageBucket: 'agritek-c8b4f.appspot.com',
    iosBundleId: 'com.example.agritek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9ZFfWaYn8ZrAYSZU25b47P-n1sFRY1Dk',
    appId: '1:464056634750:ios:4f18d60edd1fadce1ab72f',
    messagingSenderId: '464056634750',
    projectId: 'agritek-c8b4f',
    storageBucket: 'agritek-c8b4f.appspot.com',
    iosBundleId: 'com.example.agritek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDikAE3m7oz76frgBJzd1rOUtBD51rTcwI',
    appId: '1:464056634750:web:6e2149834f22c69d1ab72f',
    messagingSenderId: '464056634750',
    projectId: 'agritek-c8b4f',
    authDomain: 'agritek-c8b4f.firebaseapp.com',
    storageBucket: 'agritek-c8b4f.appspot.com',
  );

}